### ISSUE TITLE
Add Contributing doc

### ISSUE THREAD

**Issue by tsriram** [FormidableLabs/react-live#100]
Hi :wave: 

I wanted to try fix #41 (no idea how to fix it, just wanted to figure out!) but I'm finding it difficult to set up my local environment. I guess I'll have to use `demo` app to test any changes I make to the library. I tried running `yarn dev` in the `demo` project but it is throwing an error when I try to access the app. I guess I'll have to run `yarn build` in the library repo first since `demo` has `react-live` dependency mentioned with file:// URL? I tried that too but I couldn't get it running.

Would be great if you could provide some high level steps to get this running locally. I'd be happy to add CONTRIBUTING.md if it's okay.

This is the error I see when I try to access demo app on localhost:3000 (it first says it's compiled successfully)

```
Error: Cannot find module "react-live/lib/constants/css"
    at Object../pages/_document.js (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/_document.js:86:7)
    at __webpack_require__ (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/webpack/bootstrap 5fa49224b10a4ee2b705:21:1)
    at Object.1 (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/_document.js:233:18)
    at __webpack_require__ (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/webpack/bootstrap 5fa49224b10a4ee2b705:21:1)
    at module.exports../pages/_document.js.Object.defineProperty.value (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/webpack/bootstrap 5fa49224b10a4ee2b705:68:1)
    at Object.<anonymous> (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/_document.js:73:10)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at _callee$ (/home/tsriram/code/oss/react-live/demo/node_modules/next/dist/server/require.js:33:46)
    at tryCatch (/home/tsriram/code/oss/react-live/demo/node_modules/next/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/tsriram/code/oss/react-live/demo/node_modules/next/node_modules/regenerator-runtime/runtime.js:296:22)
Error: Cannot find module "react-live/lib/constants/css"
    at Object../pages/_document.js (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/_document.js:86:7)
    at __webpack_require__ (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/webpack/bootstrap 5fa49224b10a4ee2b705:21:1)
    at Object.1 (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/_document.js:233:18)
    at __webpack_require__ (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/webpack/bootstrap 5fa49224b10a4ee2b705:21:1)
    at module.exports../pages/_document.js.Object.defineProperty.value (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/webpack/bootstrap 5fa49224b10a4ee2b705:68:1)
    at Object.<anonymous> (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/_document.js:73:10)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at _callee$ (/home/tsriram/code/oss/react-live/demo/node_modules/next/dist/server/require.js:33:46)
    at tryCatch (/home/tsriram/code/oss/react-live/demo/node_modules/next/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/tsriram/code/oss/react-live/demo/node_modules/next/node_modules/regenerator-runtime/runtime.js:296:22)
Error: Cannot find module "react-live/lib/constants/css"
    at Object../pages/_document.js (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/_document.js:86:7)
    at __webpack_require__ (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/webpack/bootstrap 5fa49224b10a4ee2b705:21:1)
    at Object.1 (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/_document.js:233:18)
    at __webpack_require__ (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/webpack/bootstrap 5fa49224b10a4ee2b705:21:1)
    at module.exports../pages/_document.js.Object.defineProperty.value (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/webpack/bootstrap 5fa49224b10a4ee2b705:68:1)
    at Object.<anonymous> (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/_document.js:73:10)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at _callee$ (/home/tsriram/code/oss/react-live/demo/node_modules/next/dist/server/require.js:33:46)
    at tryCatch (/home/tsriram/code/oss/react-live/demo/node_modules/next/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/tsriram/code/oss/react-live/demo/node_modules/next/node_modules/regenerator-runtime/runtime.js:296:22)
(node:12827) UnhandledPromiseRejectionWarning: Error: Cannot find module "react-live/lib/constants/css"
    at Object../pages/_document.js (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/_document.js:86:7)
    at __webpack_require__ (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/webpack/bootstrap 5fa49224b10a4ee2b705:21:1)
    at Object.1 (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/_document.js:233:18)
    at __webpack_require__ (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/webpack/bootstrap 5fa49224b10a4ee2b705:21:1)
    at module.exports../pages/_document.js.Object.defineProperty.value (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/webpack/bootstrap 5fa49224b10a4ee2b705:68:1)
    at Object.<anonymous> (/home/tsriram/code/oss/react-live/demo/.next/dist/bundles/pages/_document.js:73:10)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at _callee$ (/home/tsriram/code/oss/react-live/demo/node_modules/next/dist/server/require.js:33:46)
    at tryCatch (/home/tsriram/code/oss/react-live/demo/node_modules/next/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/tsriram/code/oss/react-live/demo/node_modules/next/node_modules/regenerator-runtime/runtime.js:296:22)
(node:12827) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by sofiapoh** [comment]
This is definitely something I want to add sooner than later! We're currently working on rewriting the api so I'm not encouraging too many big PR's to avoid duplicate work. I'll see if I get some time this week to fix/add steps to get the demo running

**Comment by tsriram** [comment]
Great, thanks :+1:
